
CREATE TABLE IF NOT EXISTS Users
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Roles
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Title  VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS UserRoles
(
    UserID INT NOT NULL,
    RoleID INT NOT NULL,
    PRIMARY KEY (UserID, RoleID),
    FOREIGN KEY (UserID) REFERENCES Users (ID),
    FOREIGN KEY (RoleID) REFERENCES Roles (ID)
);


CREATE TABLE IF NOT EXISTS Sections
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    SectionName VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS Topics
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    SectionID INT NOT NULL,
    FOREIGN KEY (SectionID) REFERENCES Sections (ID)
);


CREATE TABLE IF NOT EXISTS Questions
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    TopicID      INT  NOT NULL,
    UserID       INT  NOT NULL,
    QuestionText TEXT NOT NULL,
    FOREIGN KEY (TopicID) REFERENCES Topics (ID),
    FOREIGN KEY (UserID) REFERENCES Users (ID)
);


CREATE TABLE IF NOT EXISTS Answers
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    QuestionID INT  NOT NULL,
    UserID     INT  NOT NULL,
    AnswerText TEXT NOT NULL,
    FOREIGN KEY (QuestionID) REFERENCES Questions (ID),
    FOREIGN KEY (UserID) REFERENCES Users (ID)
);


CREATE TABLE IF NOT EXISTS Views
(
    ViewID     INT AUTO_INCREMENT PRIMARY KEY,
    UserID     INT NOT NULL,
    QuestionID INT,
    AnswerID   INT,
    FOREIGN KEY (UserID) REFERENCES Users (ID),
    FOREIGN KEY (QuestionID) REFERENCES Questions (ID),
    FOREIGN KEY (AnswerID) REFERENCES Answers (ID),
    CHECK (QuestionID IS NOT NULL OR AnswerID IS NOT NULL)
);


CREATE TABLE IF NOT EXISTS Reactions
(
    ReactionID INT AUTO_INCREMENT PRIMARY KEY,
    UserID     INT                      NOT NULL,
    QuestionID INT,
    AnswerID   INT,
    Type       ENUM ('Like', 'Dislike') NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users (ID),
    FOREIGN KEY (QuestionID) REFERENCES Questions (ID),
    FOREIGN KEY (AnswerID) REFERENCES Answers (ID),
    CHECK (QuestionID IS NOT NULL OR AnswerID IS NOT NULL)
);
